name: Test and lint

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main

jobs:
  Test-format-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          cache: bun
      - name: Install dependencies
        run: |
          bun install
      - name: Lint and format
        run: |
          bun lint
          bun format
      - name: Test
        run: |
          bun run test
