name: Test and lint

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: yarn
      - name: Install dependencies
        run: |
          yarn install
      - name: Lint and format
        run: |
          yarn lint
          yarn format
      - name: Test
        run: |
          yarn test
