name: Test and lint

on:
  pull_request:
    types:
      - opened
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm
      - name: Install dependencies
        run: |
          npm install
      - name: Lint and format
        run: |
          npm run lint
          npm run format
      - name: Test
        run: |
          npm run test
